# Generated by Django 2.1.7 on 2019-04-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20190407_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('introduce', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=50)),
            ],
        ),
    ]
