# Generated by Django 2.1.7 on 2019-04-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='time',
            field=models.DateTimeField(max_length=50),
        ),
    ]
