# Generated by Django 2.1.7 on 2019-04-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20190407_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
