# Generated by Django 2.1.7 on 2019-04-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20190409_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='places',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='places',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
