# Generated by Django 2.1.7 on 2019-04-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20190409_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='time',
            field=models.TimeField(),
        ),
    ]
