# Generated by Django 2.1.7 on 2019-04-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20190409_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
