# Generated by Django 2.1.7 on 2019-04-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20190409_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='address',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='places',
            name='introduce',
            field=models.TextField(max_length=2000),
        ),
    ]
