# Generated by Django 2.1.7 on 2019-04-12 12:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20190410_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='publishtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 12, 12, 19, 6, 999829, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
    ]
