# Generated by Django 2.1.7 on 2019-04-12 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_places_publishtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenicspot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('introduce', models.TextField(max_length=2000)),
                ('address', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='images')),
                ('opentime', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='places',
            name='address',
        ),
        migrations.RemoveField(
            model_name='places',
            name='image',
        ),
        migrations.RemoveField(
            model_name='places',
            name='time',
        ),
        migrations.AddField(
            model_name='places',
            name='price',
            field=models.IntegerField(default=3000),
        ),
        migrations.AddField(
            model_name='scenicspot',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Places'),
        ),
    ]
