# Generated by Django 2.1.7 on 2019-04-14 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20190413_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='cost',
            field=models.IntegerField(default=3000),
        ),
        migrations.AddField(
            model_name='places',
            name='hashospital',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='places',
            name='keywords',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='places',
            name='spotticket',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='places',
            name='traffic_air',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='places',
            name='traffic_highrail',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='places',
            name='traffic_port',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='places',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
