# Generated by Django 2.1.7 on 2019-04-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20190414_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='places',
            name='traffic_air',
        ),
        migrations.RemoveField(
            model_name='places',
            name='traffic_highrail',
        ),
        migrations.RemoveField(
            model_name='places',
            name='traffic_port',
        ),
        migrations.AddField(
            model_name='places',
            name='traffic',
            field=models.CharField(default='高铁', max_length=100),
        ),
        migrations.AlterField(
            model_name='places',
            name='hashospital',
            field=models.CharField(default='有三甲医院', max_length=50),
        ),
        migrations.AlterField(
            model_name='places',
            name='price',
            field=models.CharField(default='高', max_length=50),
        ),
        migrations.AlterField(
            model_name='places',
            name='spotticket',
            field=models.CharField(default='贵', max_length=50),
        ),
    ]
