# Generated by Django 2.1.7 on 2019-04-14 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20190414_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='places',
            old_name='hashospital',
            new_name='hospital',
        ),
    ]
