# Generated by Django 2.1.7 on 2019-04-20 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_auto_20190418_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('time', models.DateTimeField(verbose_name='date published')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Places')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Users')),
            ],
        ),
    ]
