# Generated by Django 2.1.7 on 2019-04-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_shares'),
    ]

    operations = [
        migrations.AddField(
            model_name='shares',
            name='image',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
    ]
