# Generated by Django 2.1.7 on 2019-04-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_shares_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shares',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
